version: '3.7'

services:
  nginx:
    build: ./nginx
    ports:
      - '8000:8000'
      - '443:443'
    depends_on:
      - app
    restart: always

  app:
    build: ./app
    command: uvicorn main:app --host 0.0.0.0 --port 8001 --reload
    ports:
      - '8001:8001'
    volumes:
      - ./app:/app/
    container_name: app
